### ISSUE TITLE
Release for kinetic

### ISSUE THREAD

**Issue by stwirth** [ccny-ros-pkg/scan_tools#51]
Hi, could we get a release of scan_tools for ROS kinetic please?
csm has been released for kinetic recently https://github.com/ros/rosdistro/pull/14128.

Thanks!

**Comment by 130s** [comment]
`csm` for Kinetic has been failing to build on ROS buildfarm (e.g. [this](http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__csm__ubuntu_xenial_amd64__binary/3/console)) so that should be fixed first. 
I won't be able to work on that for a few weeks at least. If someone can give it a shot that'll be great.

**Comment by stwirth** [comment]
latest build for csm succeeded: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__csm__ubuntu_xenial_amd64__binary/6/

**Comment by 130s** [comment]
https://github.com/ros/rosdistro/pull/14260 Done

**Comment by stwirth** [comment]
Thanks!
