### ISSUE TITLE
 Error in scan matching

### ISSUE THREAD

**Issue by mgrallos** [ccny-ros-pkg/scan_tools#89]
I got this error message 

```
:err: 	: before trimming, only 47 correspondences.
:err: icp: ICP failed for some reason.
```
I don't know what causes it.

**Comment by mgrallos** [comment]
and how to fix it

**Comment by cst0** [comment]
If this error message comes up from time to time but doesn't otherwise impede operation, I wouldn't worry about it: laser data comes in so quickly that a few missed scans is no big deal. My best guess is that it's some edge case in the underlying implementation of the algorithm, but without more detail it's hard to say.

If you're able to provide more information, and in particular steps to replicate, I'm happy to discuss further. But for now, I'll have to close this as inactive and lacking replication steps.
